name: food
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1 
  firebase_auth_mocks: ^0.14.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^0.8.6
  flutter_lints: ^3.0.0

flutter:
  assets:
    - Momo_images/Rider.png
    - Momo_images/Consumer.png
    - Momo_images/Momo logo.png
    - Momo_images/Grocery.png
    - Momo_images/momowhite.png
    - Momo_images/Google.png
    - Momo_images/Facebook.png
    - Momo_images/back.png
    - Momo_images/Account.png
    - Momo_images/Expand Arrow.png
    - Momo_images/Photo Gallery.png
    - Momo_images/egg.png
    - Momo_images/bread.png
    - Momo_images/home.png
    - Momo_images/chat.png
    - Momo_images/My List.png
    - Momo_images/nestle.png
    - Momo_images/profile.png
    - Momo_images/iPhone-status-bar(upper).png
    - Momo_images/Juan Deck.png
    - Momo_images/Juliet.png
    - Momo_images/Romeo.png
    - Momo_images/fluent-arrow.png
    - Momo_images/Card Payment.png
    - Momo_images/Help.png
    - Momo_images/Settings.png
    - Momo_images/Place Marker.png
    - Momo_images/User.png
    - Momo_images/check.png
    - Momo_images/gcash.png
    - Momo_images/mdi_account-cash.png
    - Momo_images/solar_notification.png
    - Momo_images/ph_key.png
    - Momo_images/ic_outline-delete.png
    - Momo_images/Vector.png
    - Momo_images/No list.png
    - Momo_images/check icon.png
    - Momo_images/find.png
    - Momo_images/Notification icon.png
    - Momo_images/gcash cat.png
    - Momo_images/Invisible.png
    - Momo_images/MOMOw.png
    - Momo_images/motorwhite.png     
    - Momo_images/motorwhitew.png
    - Momo_images/Group 840.png
    - Momo_images/chat (1).png
    - Momo_images/dashboard.png
    - Momo_images/eos-icons_admin.png
    - Momo_images/grocery List.png
    - Momo_images/iconamoon_history-bold.png
    - Momo_images/Maki_grocery.png
    - Momo_images/material-symbols_cancel-rounded.png
    - Momo_images/typcn_th-menu.png
    - Momo_images/userlist.png
    - Momo_images/vec.png
    - Momo_images/mdi_google-analytics.png
    - Momo_images/stash_paperplane-solid.png
    - Momo_images/material-symbols_map.png
    - Momo_images/greenback.png
    - Momo_images/c.png
    - Momo_images/v.png
    - Momo_images/logout.png
    - Momo_images/Search.png